# .golangci.yml
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - stylecheck
    - misspell

  disable:
    - revive
    - gocyclo
    - bodyclose
    - nilerr
    - whitespace

linters-settings:
  stylecheck:
    checks: ["all", "-ST1003"]
  
  staticcheck:
    checks: ["all", "-SA1019", "-ST1000"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    
    - linters:
        - stylecheck
      text: "should have comment"
    
    - linters:
        - staticcheck
      text: "exported.*should have comment"

  exclude-dirs:
    - vendor
    - third_party
    - testdata

  exclude-files:
    - ".*_test.go"
    - ".*/test/.*"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true